#!/bin/bash
# test_lifecycle.sh — End-to-end lifecycle integration test for CDD.
#
# Verifies that tools/cdd/status.sh and tools/critic/run.sh correctly
# report feature lifecycle state and role status columns through the
# complete feature lifecycle: TODO -> TESTING -> COMPLETE -> spec edit -> TODO.
#
# Usage: tools/cdd/test_lifecycle.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Project root detection (Section 2.11)
if [ -n "${AGENTIC_PROJECT_ROOT:-}" ] && [ -d "$AGENTIC_PROJECT_ROOT" ]; then
    PROJECT_ROOT="$AGENTIC_PROJECT_ROOT"
else
    if [ -d "$SCRIPT_DIR/../../../.agentic_devops" ]; then
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
    elif [ -d "$SCRIPT_DIR/../../.agentic_devops" ]; then
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
    else
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
    fi
fi
export AGENTIC_PROJECT_ROOT="$PROJECT_ROOT"
cd "$PROJECT_ROOT"

TEMP_FEATURE="features/_test_lifecycle_temp.md"
TEMP_TESTS_DIR="tests/_test_lifecycle_temp"
PRE_TEST_SHA="$(git rev-parse HEAD)"

PASSED=0
FAILED=0

# ============================================================
# Cleanup (runs on exit via trap)
# ============================================================
cleanup() {
    echo ""
    echo "--- Cleanup ---"
    git reset --hard "$PRE_TEST_SHA" >/dev/null 2>&1 || true
    rm -rf "$TEMP_FEATURE" "$TEMP_TESTS_DIR"
    # Restore critic.json state for real features
    bash tools/critic/run.sh >/dev/null 2>&1 || true
    echo "Cleanup complete."
}
trap cleanup EXIT

# ============================================================
# Helpers
# ============================================================

# Get lifecycle state for the temp feature from feature_status.json
get_lifecycle() {
    python3 -c "
import json, sys
try:
    with open('.agentic_devops/cache/feature_status.json') as f:
        d = json.load(f)
    for state in ('complete', 'testing', 'todo'):
        for entry in d['features'].get(state, []):
            if '_test_lifecycle_temp' in entry.get('file', ''):
                print(state.upper())
                sys.exit(0)
    print('NOT_FOUND')
except Exception as e:
    print('ERROR:' + str(e))
"
}

# Get role_status field from critic.json
get_role() {
    local role="$1"
    python3 -c "
import json, sys
try:
    with open('tests/_test_lifecycle_temp/critic.json') as f:
        d = json.load(f)
    print(d.get('role_status', {}).get('$role', 'MISSING'))
except Exception as e:
    print('ERROR:' + str(e))
"
}

# Assert a value matches expected
assert_eq() {
    local label="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        return 0
    else
        echo "  FAIL: $label: expected=$expected actual=$actual"
        FAILED=$((FAILED + 1))
        return 1
    fi
}

# Refresh cycle: status.sh -> critic -> (read results)
refresh() {
    bash tools/cdd/status.sh >/dev/null 2>&1
    bash tools/critic/run.sh >/dev/null 2>&1
}

# ============================================================
# Stage 1: TODO with No Tests
# ============================================================

cat > "$TEMP_FEATURE" << 'FEATURE'
# Feature: Lifecycle Integration Test Fixture

> Label: "Test: Lifecycle Fixture"
> Category: "Testing"
> Prerequisite: features/arch_critic_policy.md

## 1. Overview
Temporary feature used exclusively by the CDD lifecycle integration test.

## 2. Requirements

### 2.1 Placeholder
* The fixture feature must exist with valid structure for Spec Gate validation.

## 3. Scenarios

### Automated Scenarios

#### Scenario: Fixture Passes Spec Gate
    Given this feature file exists
    When the Critic tool runs the Spec Gate
    Then section_completeness reports PASS

### Manual Scenarios (Human Verification Required)

#### Scenario: Manual Placeholder
    Given this feature is in TESTING state
    When the QA Agent reviews
    Then the QA Agent verifies manually

## 4. Implementation Notes
* This file is auto-generated by test_lifecycle.sh and deleted on cleanup.
FEATURE

git add "$TEMP_FEATURE"
git commit -m "test(lifecycle): add temp fixture feature" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TODO" "$lifecycle"   || stage_ok=false
assert_eq "builder"   "TODO" "$builder"     || stage_ok=false
assert_eq "qa"        "N/A"  "$qa"          || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TODO with No Tests'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 2: TODO with Passing Tests
# ============================================================

mkdir -p "$TEMP_TESTS_DIR"
echo '{"status": "PASS"}' > "$TEMP_TESTS_DIR/tests.json"
git add -f "$TEMP_TESTS_DIR/tests.json"
git commit -m "test(lifecycle): add temp test results" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TODO"  "$lifecycle"  || stage_ok=false
assert_eq "builder"   "TODO"  "$builder"    || stage_ok=false
assert_eq "qa"        "CLEAN" "$qa"         || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TODO with Passing Tests'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 3: TESTING
# ============================================================

git commit --allow-empty -m "status(lifecycle): [Ready for Verification features/_test_lifecycle_temp.md]" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TESTING" "$lifecycle" || stage_ok=false
assert_eq "builder"   "DONE"    "$builder"   || stage_ok=false
assert_eq "qa"        "TODO"    "$qa"        || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TESTING'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 4: COMPLETE
# ============================================================

git commit --allow-empty -m "status(lifecycle): [Complete features/_test_lifecycle_temp.md]" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "COMPLETE" "$lifecycle" || stage_ok=false
assert_eq "builder"   "DONE"     "$builder"   || stage_ok=false
assert_eq "qa"        "CLEAN"    "$qa"        || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- COMPLETE'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 5: Spec Edit Resets to TODO
# ============================================================

# Ensure file mtime is strictly after the [Complete] commit timestamp
sleep 1

# Modify spec content above the User Testing Discoveries section
sed -i '' 's/Placeholder/Placeholder (modified)/' "$TEMP_FEATURE"
git add "$TEMP_FEATURE"
git commit -m "test(lifecycle): modify spec content" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)

stage_ok=true
assert_eq "lifecycle" "TODO" "$lifecycle" || stage_ok=false
assert_eq "builder"   "TODO" "$builder"   || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- Spec Edit Resets to TODO'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Write test results
# ============================================================

TOTAL=$((PASSED + FAILED))
if [ "$FAILED" -eq 0 ]; then
    STATUS="PASS"
else
    STATUS="FAIL"
fi

# Write to tests/cdd_status_monitor/tests.json
RESULTS_DIR="tests/cdd_status_monitor"
mkdir -p "$RESULTS_DIR"
cat > "$RESULTS_DIR/tests.json" << EOF
{"status": "$STATUS", "tests": $TOTAL, "failures": $FAILED, "tool": "cdd_lifecycle", "runner": "bash"}
EOF

echo ""
echo "--- Results: $PASSED passed, $FAILED failed ---"

# The Cleanup scenario is verified by the trap itself
echo '[Scenario] Lifecycle Integration -- Cleanup'

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
exit 0
