#!/bin/bash
# test_lifecycle.sh — End-to-end lifecycle integration test for CDD.
#
# Verifies that tools/cdd/status.sh and tools/critic/run.sh correctly
# report feature lifecycle state and role status columns through the
# complete feature lifecycle: TODO -> TESTING -> COMPLETE -> spec edit -> TODO.
#
# Usage: tools/cdd/test_lifecycle.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Project root detection (Section 2.11)
if [ -n "${PURLIN_PROJECT_ROOT:-}" ] && [ -d "$PURLIN_PROJECT_ROOT" ]; then
    PROJECT_ROOT="$PURLIN_PROJECT_ROOT"
else
    if [ -d "$SCRIPT_DIR/../../../.purlin" ]; then
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
    elif [ -d "$SCRIPT_DIR/../../.purlin" ]; then
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
    else
        PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
    fi
fi
export PURLIN_PROJECT_ROOT="$PROJECT_ROOT"

# Source shared Python resolver (python_environment.md §2.2)
source "$SCRIPT_DIR/../resolve_python.sh"

cd "$PROJECT_ROOT"

TEMP_FEATURE="features/_test_lifecycle_temp.md"
TEMP_TESTS_DIR="tests/_test_lifecycle_temp"
PRE_TEST_SHA="$(git rev-parse HEAD)"

PASSED=0
FAILED=0

# ============================================================
# Cleanup (runs on exit via trap)
# ============================================================
cleanup() {
    echo ""
    echo "--- Cleanup ---"
    # Stop any CDD server started during tests
    bash "$SCRIPT_DIR/stop.sh" 2>/dev/null || true
    # Mixed reset: undo test commits but preserve the working tree.
    # Unlike --hard, this does NOT destroy uncommitted code changes.
    git reset "$PRE_TEST_SHA" >/dev/null 2>&1 || true
    # Remove temp files from working tree (untracked after reset)
    rm -rf "$TEMP_FEATURE" "$TEMP_TESTS_DIR"
    # Restore critic.json state for real features (status.sh auto-runs Critic)
    bash tools/cdd/status.sh >/dev/null 2>&1 || true
    echo "Cleanup complete."
}
trap cleanup EXIT

# ============================================================
# Helpers
# ============================================================

# Get lifecycle state for the temp feature from feature_status.json
get_lifecycle() {
    "$PYTHON_EXE" -c "
import json, sys
try:
    with open('.purlin/cache/feature_status.json') as f:
        d = json.load(f)
    for state in ('complete', 'testing', 'todo'):
        for entry in d['features'].get(state, []):
            if '_test_lifecycle_temp' in entry.get('file', ''):
                print(state.upper())
                sys.exit(0)
    print('NOT_FOUND')
except Exception as e:
    print('ERROR:' + str(e))
"
}

# Get role_status field from critic.json
get_role() {
    local role="$1"
    "$PYTHON_EXE" -c "
import json, sys
try:
    with open('tests/_test_lifecycle_temp/critic.json') as f:
        d = json.load(f)
    print(d.get('role_status', {}).get('$role', 'MISSING'))
except Exception as e:
    print('ERROR:' + str(e))
"
}

# Assert a value matches expected
assert_eq() {
    local label="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        return 0
    else
        echo "  FAIL: $label: expected=$expected actual=$actual"
        FAILED=$((FAILED + 1))
        return 1
    fi
}

# Refresh cycle: status.sh auto-runs Critic (Section 2.6), so one call suffices.
refresh() {
    bash tools/cdd/status.sh >/dev/null 2>&1
}

# ============================================================
# Stage 1: TODO with No Tests
# ============================================================

cat > "$TEMP_FEATURE" << 'FEATURE'
# Feature: Lifecycle Integration Test Fixture

> Label: "Test: Lifecycle Fixture"
> Category: "Testing"
> Prerequisite: features/policy_critic.md

## 1. Overview
Temporary feature used exclusively by the CDD lifecycle integration test.

## 2. Requirements

### 2.1 Placeholder
* The fixture feature must exist with valid structure for Spec Gate validation.

## 3. Scenarios

### Automated Scenarios

#### Scenario: Fixture Passes Spec Gate
    Given this feature file exists
    When the Critic tool runs the Spec Gate
    Then section_completeness reports PASS

### Manual Scenarios (Human Verification Required)

#### Scenario: Manual Placeholder
    Given this feature is in TESTING state
    When the QA Agent reviews
    Then the QA Agent verifies manually

## 4. Implementation Notes
* This file is auto-generated by test_lifecycle.sh and deleted on cleanup.
FEATURE

git add "$TEMP_FEATURE"
git commit -m "test(lifecycle): add temp fixture feature" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TODO" "$lifecycle"   || stage_ok=false
assert_eq "builder"   "TODO" "$builder"     || stage_ok=false
assert_eq "qa"        "N/A"  "$qa"          || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TODO with No Tests'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 2: TODO with Passing Tests
# ============================================================

mkdir -p "$TEMP_TESTS_DIR"
echo '{"status": "PASS", "passed": 1, "failed": 0, "total": 1, "test_file": "tools/cdd/test_lifecycle.sh"}' > "$TEMP_TESTS_DIR/tests.json"
git add -f "$TEMP_TESTS_DIR/tests.json"
git commit -m "test(lifecycle): add temp test results" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TODO"  "$lifecycle"  || stage_ok=false
assert_eq "builder"   "TODO"  "$builder"    || stage_ok=false
assert_eq "qa"        "CLEAN" "$qa"         || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TODO with Passing Tests'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 3: TESTING
# ============================================================

git commit --allow-empty -m "status(lifecycle): [Ready for Verification features/_test_lifecycle_temp.md]" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "TESTING" "$lifecycle" || stage_ok=false
assert_eq "builder"   "DONE"    "$builder"   || stage_ok=false
assert_eq "qa"        "TODO"    "$qa"        || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- TESTING'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 4: COMPLETE
# ============================================================

# Ensure [Complete] commit timestamp is strictly after [Ready for Verification]
sleep 1

git commit --allow-empty -m "status(lifecycle): [Complete features/_test_lifecycle_temp.md] [Verified]" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)
qa=$(get_role qa)

stage_ok=true
assert_eq "lifecycle" "COMPLETE" "$lifecycle" || stage_ok=false
assert_eq "builder"   "DONE"     "$builder"   || stage_ok=false
assert_eq "qa"        "CLEAN"    "$qa"        || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- COMPLETE'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 5: Spec Edit Resets to TODO
# ============================================================

# Ensure file mtime is strictly after the [Complete] commit timestamp
sleep 1

# Modify spec content above the User Testing Discoveries section
sed -i '' 's/Placeholder/Placeholder (modified)/' "$TEMP_FEATURE"
git add "$TEMP_FEATURE"
git commit -m "test(lifecycle): modify spec content" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)

stage_ok=true
assert_eq "lifecycle" "TODO" "$lifecycle" || stage_ok=false
assert_eq "builder"   "TODO" "$builder"   || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- Spec Edit Resets to TODO'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 5a: Abbreviated Status Commit Format
# ============================================================
# The feature is in TODO state from Stage 5. Use abbreviated format
# to mark it complete: feat(<scope>): [Complete]

sleep 1

git commit --allow-empty -m "feat(_test_lifecycle_temp): [Complete] all scenarios passing" --quiet

refresh
lifecycle=$(get_lifecycle)
builder=$(get_role builder)

stage_ok=true
assert_eq "lifecycle" "COMPLETE" "$lifecycle" || stage_ok=false
assert_eq "builder"   "DONE"    "$builder"   || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Lifecycle Integration -- Abbreviated Status Commit Format'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 5b: Abbreviated Status Commit With Non-Existent Feature Scope
# ============================================================
# A commit with a scope that doesn't correspond to any feature file
# must be silently ignored.

git commit --allow-empty -m "feat(nonexistent_feature): [Complete] something" --quiet

refresh

# Check that no feature entry was created for nonexistent_feature
nonexistent_check=$("$PYTHON_EXE" -c "
import json, sys
try:
    with open('.purlin/cache/feature_status.json') as f:
        d = json.load(f)
    for state in ('complete', 'testing', 'todo'):
        for entry in d['features'].get(state, []):
            if 'nonexistent_feature' in entry.get('file', ''):
                print('FOUND')
                sys.exit(0)
    print('NOT_FOUND')
except Exception as e:
    print('ERROR:' + str(e))
")

stage_ok=true
assert_eq "nonexistent_ignored" "NOT_FOUND" "$nonexistent_check" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Abbreviated Status Commit With Non-Existent Feature Scope'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 5c: Canonical Status Commit Format Takes Precedence Over Abbreviated
# ============================================================
# Reset the temp feature to TODO, then make a canonical [Complete] commit,
# then a later abbreviated [Complete] commit that also modifies the file.
# The most recent matching commit determines lifecycle state.

sleep 1

# Reset to TODO by modifying spec
sed -i '' 's/Placeholder (modified)/Placeholder (reset)/' "$TEMP_FEATURE"
git add "$TEMP_FEATURE"
git commit -m "test(lifecycle): reset for precedence test" --quiet

sleep 1

# Canonical complete
git commit --allow-empty -m "status(lifecycle): [Complete features/_test_lifecycle_temp.md] [Verified]" --quiet

sleep 1

# Later abbreviated complete that also touches the feature file
echo "## Precedence Test Addendum" >> "$TEMP_FEATURE"
git add "$TEMP_FEATURE"
git commit -m "feat(_test_lifecycle_temp): [Complete] updated" --quiet

refresh
lifecycle=$(get_lifecycle)

stage_ok=true
# The abbreviated commit is most recent — its timestamp matches the file mod.
# Since complete_ts == file_mod_ts, spec_content_unchanged returns False
# (content changed), so lifecycle should be COMPLETE only if the abbreviated
# commit's timestamp is used. The abbreviated commit IS the most recent
# [Complete] and its timestamp equals the file mtime (same commit), so
# spec_content_unchanged compares content at that hash which IS the current
# content. Result: COMPLETE.
assert_eq "lifecycle" "COMPLETE" "$lifecycle" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Canonical Status Commit Format Takes Precedence Over Abbreviated'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 6: Theme Toggle LocalStorage Behavior (HTML inspection)
# ============================================================

html=$("$PYTHON_EXE" -c "
import sys, os
sys.path.insert(0, os.path.join(os.environ['PURLIN_PROJECT_ROOT'], 'tools', 'cdd'))
from serve import generate_html
print(generate_html())
" 2>/dev/null || echo "ERROR_GENERATING_HTML")

has_fouc=$(echo "$html" | grep -c "localStorage.getItem" || true)
has_toggle=$(echo "$html" | grep -c "toggleTheme" || true)
has_setitem=$(echo "$html" | grep -c "localStorage.setItem" || true)
has_datatheme=$(echo "$html" | grep -c "data-theme" || true)
has_light_css=$(echo "$html" | grep -c "data-theme='light'" || true)

[ "$has_fouc" -gt 0 ] && fouc="YES" || fouc="NO"
[ "$has_toggle" -gt 0 ] && toggle="YES" || toggle="NO"
[ "$has_setitem" -gt 0 ] && setitem="YES" || setitem="NO"
[ "$has_datatheme" -gt 0 ] && datatheme="YES" || datatheme="NO"
[ "$has_light_css" -gt 0 ] && lightcss="YES" || lightcss="NO"

stage_ok=true
assert_eq "FOUC_localStorage_read"  "YES" "$fouc"      || stage_ok=false
assert_eq "toggleTheme_function"    "YES" "$toggle"     || stage_ok=false
assert_eq "localStorage_setItem"    "YES" "$setitem"    || stage_ok=false
assert_eq "data-theme_attribute"    "YES" "$datatheme"  || stage_ok=false
assert_eq "light_theme_CSS"         "YES" "$lightcss"   || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Theme Toggle LocalStorage Behavior'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 7: Multiple Projects on Same Machine
# ============================================================
# Verifies that start.sh uses --project-root scoped process
# detection and per-project port files, so two projects can
# run CDD servers independently.

# Create two temporary project directories
PROJECT_A=$(mktemp -d)
PROJECT_B=$(mktemp -d)
mkdir -p "$PROJECT_A/.purlin/runtime" "$PROJECT_B/.purlin/runtime"

# Simulate different port files for each project
echo "8080" > "$PROJECT_A/.purlin/runtime/cdd.port"
echo "9090" > "$PROJECT_B/.purlin/runtime/cdd.port"

stage_ok=true

# Port files are independent (different ports per project)
PORT_A=$(cat "$PROJECT_A/.purlin/runtime/cdd.port")
PORT_B=$(cat "$PROJECT_B/.purlin/runtime/cdd.port")
assert_eq "project_A_port" "8080" "$PORT_A"                     || stage_ok=false
assert_eq "project_B_port" "9090" "$PORT_B"                     || stage_ok=false

# start.sh process detection uses grep -F PROJECT_ROOT — verify
# the grep pattern for project A does NOT match project B
if echo "--project-root $PROJECT_A" | grep -qF "$PROJECT_B"; then
    echo "  FAIL: project root grep collision"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi

# serve.py --project-root flag is present in the launch command template
if ! grep -q -- "--project-root" "$SCRIPT_DIR/start.sh"; then
    echo "  FAIL: start.sh missing --project-root"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi

if $stage_ok; then
    echo '[Scenario] Multiple projects on same machine'
    PASSED=$((PASSED + 1))
fi

rm -rf "$PROJECT_A" "$PROJECT_B"

# ============================================================
# Server Lifecycle — helpers
# ============================================================
PORT_FILE="$PROJECT_ROOT/.purlin/runtime/cdd.port"
RUNTIME_DIR="$PROJECT_ROOT/.purlin/runtime"

stop_server_quiet() {
    bash "$SCRIPT_DIR/stop.sh" 2>/dev/null || true
    sleep 0.3
}

# ============================================================
# Stage 8: Start prints clickable URL with auto-selected port
# Also verifies: port file written, ps visibility, no cdd.pid,
# no cdd_port config dependency (Scenarios 1, 9, 10, 11)
# ============================================================
stop_server_quiet
rm -f "$PORT_FILE"

START_OUTPUT=$(bash "$SCRIPT_DIR/start.sh" 2>&1)
URL_LINE=$(echo "$START_OUTPUT" | grep -o "http://localhost:[0-9]*" || echo "NO_URL")
AUTO_PORT=""
if [ "$URL_LINE" != "NO_URL" ]; then
    AUTO_PORT=$(echo "$URL_LINE" | grep -o '[0-9]*$')
fi

stage_ok=true
assert_eq "url_printed" "YES" "$([ "$URL_LINE" != 'NO_URL' ] && echo YES || echo NO)" || stage_ok=false
if [ -f "$PORT_FILE" ]; then
    FILE_PORT=$(cat "$PORT_FILE")
    assert_eq "port_file_matches_url" "$AUTO_PORT" "$FILE_PORT" || stage_ok=false
else
    echo "  FAIL: port file not found after start"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi
if [ -f "$RUNTIME_DIR/cdd.pid" ]; then
    echo "  FAIL: cdd.pid file should not exist"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi
PS_MATCH=$(ps aux | grep "[s]erve.py" | grep -F -- "--project-root" | grep -cF "$PROJECT_ROOT" || true)
assert_eq "ps_shows_project_root" "YES" "$([ "$PS_MATCH" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
CONFIG_HAS_CDD_PORT=$("$PYTHON_EXE" -c "
import json
with open('$PROJECT_ROOT/.purlin/config.json') as f:
    d = json.load(f)
print('YES' if 'cdd_port' in d else 'NO')")
assert_eq "no_cdd_port_in_config" "NO" "$CONFIG_HAS_CDD_PORT" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Start prints clickable URL with auto-selected port'
    echo '[Scenario] serve.py --project-root is visible in ps'
    echo '[Scenario] Port file written before serve_forever'
    echo '[Scenario] cdd_port config key is not read'
    PASSED=$((PASSED + 4))
fi

# ============================================================
# Stage 9: Stop uses ps-based detection (server from Stage 8)
# ============================================================
STOP_OUTPUT=$(bash "$SCRIPT_DIR/stop.sh" 2>&1)

stage_ok=true
PS_AFTER_STOP=$(ps aux | grep "[s]erve.py" | grep -F -- "--project-root" | grep -cF "$PROJECT_ROOT" || true)
assert_eq "process_stopped" "0" "$PS_AFTER_STOP" || stage_ok=false
assert_eq "port_file_removed" "NO" "$([ -f "$PORT_FILE" ] && echo YES || echo NO)" || stage_ok=false
STOP_HAS_PID=$(echo "$STOP_OUTPUT" | grep -c "PID" || true)
assert_eq "stop_mentions_pid" "YES" "$([ "$STOP_HAS_PID" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Stop uses ps-based detection'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 10: Start with explicit port via -p flag
# ============================================================
TEST_PORT=19871
START_P_OUTPUT=$(bash "$SCRIPT_DIR/start.sh" -p $TEST_PORT 2>&1)

stage_ok=true
URL_HAS_PORT=$(echo "$START_P_OUTPUT" | grep -c "http://localhost:$TEST_PORT" || true)
assert_eq "explicit_port_in_url" "YES" "$([ "$URL_HAS_PORT" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
if [ -f "$PORT_FILE" ]; then
    FILE_PORT=$(cat "$PORT_FILE")
    assert_eq "port_file_explicit" "$TEST_PORT" "$FILE_PORT" || stage_ok=false
else
    echo "  FAIL: port file not found for explicit port"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi
if $stage_ok; then
    echo '[Scenario] Start with explicit port via -p flag'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Stage 11: Restart on rerun preserves port (server from Stage 10)
# ============================================================
RESTART_OUTPUT=$(bash "$SCRIPT_DIR/start.sh" 2>&1)

stage_ok=true
RESTART_MSG=$(echo "$RESTART_OUTPUT" | grep -c "Restarted" || true)
assert_eq "restart_message" "YES" "$([ "$RESTART_MSG" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
if [ -f "$PORT_FILE" ]; then
    RESTART_PORT=$(cat "$PORT_FILE")
    assert_eq "port_preserved" "$TEST_PORT" "$RESTART_PORT" || stage_ok=false
else
    echo "  FAIL: port file missing after restart"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi
if $stage_ok; then
    echo '[Scenario] Restart on rerun preserves port'
    PASSED=$((PASSED + 1))
fi

stop_server_quiet

# ============================================================
# Stage 12: Stale port file is cleaned up
# ============================================================
stop_server_quiet
echo "55555" > "$PORT_FILE"

STALE_OUTPUT=$(bash "$SCRIPT_DIR/start.sh" 2>&1)

stage_ok=true
if [ -f "$PORT_FILE" ]; then
    FRESH_PORT=$(cat "$PORT_FILE")
    if [[ "$FRESH_PORT" =~ ^[0-9]+$ ]]; then
        assert_eq "fresh_port_valid" "YES" "YES" || stage_ok=false
    else
        echo "  FAIL: fresh port not a valid number"
        FAILED=$((FAILED + 1))
        stage_ok=false
    fi
else
    echo "  FAIL: no port file after stale cleanup start"
    FAILED=$((FAILED + 1))
    stage_ok=false
fi
STALE_URL=$(echo "$STALE_OUTPUT" | grep -c "http://localhost:" || true)
assert_eq "url_after_stale" "YES" "$([ "$STALE_URL" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Stale port file is cleaned up'
    PASSED=$((PASSED + 1))
fi

stop_server_quiet

# ============================================================
# Stage 13: Idempotent stop when not running
# ============================================================
stop_server_quiet
IDEM_OUTPUT=$(bash "$SCRIPT_DIR/stop.sh" 2>&1)
IDEM_EXIT=$?

stage_ok=true
IDEM_MSG=$(echo "$IDEM_OUTPUT" | grep -ci "not running" || true)
assert_eq "idempotent_message" "YES" "$([ "$IDEM_MSG" -gt 0 ] && echo YES || echo NO)" || stage_ok=false
assert_eq "idempotent_exit" "0" "$IDEM_EXIT" || stage_ok=false
if $stage_ok; then
    echo '[Scenario] Idempotent stop when not running'
    PASSED=$((PASSED + 1))
fi

# ============================================================
# Write test results
# ============================================================

TOTAL=$((PASSED + FAILED))
if [ "$FAILED" -eq 0 ]; then
    STATUS="PASS"
else
    STATUS="FAIL"
fi

# Write to tests/cdd_lifecycle/tests.json
RESULTS_DIR="tests/cdd_lifecycle"
mkdir -p "$RESULTS_DIR"
cat > "$RESULTS_DIR/tests.json" << EOF
{"status": "$STATUS", "passed": $PASSED, "failed": $FAILED, "total": $TOTAL, "test_file": "tools/cdd/test_lifecycle.sh"}
EOF

echo ""
echo "--- Results: $PASSED passed, $FAILED failed ---"

# The Cleanup scenario is verified by the trap itself
echo '[Scenario] Lifecycle Integration -- Cleanup'

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
exit 0
