#!/usr/bin/env bash
# tests/qa/test_project_init_regression.sh
# QA-owned regression harness for features/project_init.md
# Covers the ### QA Scenarios (@auto) listed in Section 3.
#
# Usage: bash tests/qa/test_project_init_regression.sh [--write-results]
# --write-results is accepted but is a no-op (harness_runner.py writes tests.json).
# Exit 0 = all tests passed. Exit 1 = one or more failures.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PURLIN_ROOT="${PURLIN_PROJECT_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
SUBMODULE_SRC="$PURLIN_ROOT"
PASS=0
FAIL=0
ERRORS=""
SANDBOX=""

###############################################################################
# Helpers
###############################################################################
log_pass() { PASS=$((PASS+1)); echo "PASS: $1"; }
log_fail() { FAIL=$((FAIL+1)); ERRORS="$ERRORS\nFAIL: $1"; echo "FAIL: $1"; }

cleanup_sandbox() {
    if [ -n "${SANDBOX:-}" ] && [ -d "$SANDBOX" ]; then
        rm -rf "$SANDBOX"
    fi
}

setup_sandbox() {
    SANDBOX="$(mktemp -d)"
    trap cleanup_sandbox EXIT INT TERM

    PROJECT="$SANDBOX/my-project"
    mkdir -p "$PROJECT"

    git -C "$PROJECT" init -q
    git -C "$PROJECT" commit --allow-empty -q -m "initial commit"

    # Clone current Purlin repo as simulated submodule
    git clone -q "$SUBMODULE_SRC" "$PROJECT/purlin"

    # Overlay latest uncommitted code
    cp "$SUBMODULE_SRC/tools/init.sh" "$PROJECT/purlin/tools/init.sh"
    cp "$SUBMODULE_SRC/tools/resolve_python.sh" "$PROJECT/purlin/tools/resolve_python.sh" 2>/dev/null || true
    mkdir -p "$PROJECT/purlin/tools/mcp"
    [ -f "$SUBMODULE_SRC/tools/mcp/manifest.json" ] && cp "$SUBMODULE_SRC/tools/mcp/manifest.json" "$PROJECT/purlin/tools/mcp/manifest.json"
    mkdir -p "$PROJECT/purlin/purlin-config-sample"
    [ -f "$SUBMODULE_SRC/purlin-config-sample/gitignore.purlin" ] && cp "$SUBMODULE_SRC/purlin-config-sample/gitignore.purlin" "$PROJECT/purlin/purlin-config-sample/gitignore.purlin"
    [ -f "$SUBMODULE_SRC/purlin-config-sample/CLAUDE.md.purlin" ] && cp "$SUBMODULE_SRC/purlin-config-sample/CLAUDE.md.purlin" "$PROJECT/purlin/purlin-config-sample/CLAUDE.md.purlin"
    if [ -d "$SUBMODULE_SRC/.claude/agents" ]; then
        mkdir -p "$PROJECT/purlin/.claude/agents"
        cp "$SUBMODULE_SRC/.claude/agents/"*.md "$PROJECT/purlin/.claude/agents/" 2>/dev/null || true
    fi
    if [ -d "$SUBMODULE_SRC/.claude/commands" ]; then
        mkdir -p "$PROJECT/purlin/.claude/commands"
        cp "$SUBMODULE_SRC/.claude/commands/"pl-*.md "$PROJECT/purlin/.claude/commands/" 2>/dev/null || true
    fi
    chmod +x "$PROJECT/purlin/tools/init.sh" 2>/dev/null || true
    ln -sf tools/init.sh "$PROJECT/purlin/pl-init.sh"

    cat > "$PROJECT/.gitmodules" << 'GITMOD'
[submodule "purlin"]
    path = purlin
    url = https://github.com/rlabarca/purlin.git
GITMOD

    INIT_SH="$PROJECT/purlin/tools/init.sh"

    # Remove claude from PATH to prevent MCP installation during most tests
    SAFE_PATH=""
    IFS=: read -ra DIRS <<< "$PATH"
    for dir in "${DIRS[@]}"; do
        [ -x "$dir/claude" ] && continue
        SAFE_PATH="${SAFE_PATH:+$SAFE_PATH:}$dir"
    done
}

teardown_sandbox() {
    [ -n "${SANDBOX:-}" ] && [ -d "$SANDBOX" ] && rm -rf "$SANDBOX"
    SANDBOX=""
    trap - EXIT INT TERM
}

###############################################################################
echo "=== QA Regression: project_init integration scenarios ==="
echo ""
###############################################################################

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 1: Shim Initializes Submodule on Fresh Clone
# ─────────────────────────────────────────────────────────────────────────────
echo "[S1] Shim Initializes Submodule on Fresh Clone"
setup_sandbox

# Run full init first to generate pl-init.sh
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Verify pl-init.sh was generated at project root
if [ ! -f "$PROJECT/pl-init.sh" ]; then
    log_fail "S1: pl-init.sh was not generated by full init"
    teardown_sandbox
else
    # Simulate state where tools/init.sh is missing (submodule not initialized)
    # by temporarily renaming it
    mv "$PROJECT/purlin/tools/init.sh" "$PROJECT/purlin/tools/init.sh.bak"

    OUT=$(cd "$PROJECT" && bash pl-init.sh 2>&1) || true

    # Restore
    mv "$PROJECT/purlin/tools/init.sh.bak" "$PROJECT/purlin/tools/init.sh"

    if echo "$OUT" | grep -qi "Initializing submodule\|submodule update\|init.*purlin\|purlin.*init"; then
        log_pass "S1: shim detects missing init.sh and attempts submodule init"
    elif echo "$OUT" | grep -qi "ERROR: Could not find"; then
        log_pass "S1: shim correctly detected missing init.sh (submodule init attempted but sandbox URL mismatch is expected)"
    else
        log_fail "S1: shim did not detect missing init.sh as expected (output: $(echo "$OUT" | head -3))"
    fi
    teardown_sandbox
fi

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 2: Refresh Mode Copies New and Updated Commands
# ─────────────────────────────────────────────────────────────────────────────
echo "[S2] Refresh Mode Copies New and Updated Commands"
setup_sandbox

# Full init
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Add a new command file to submodule
echo "# new cmd" > "$PROJECT/purlin/.claude/commands/pl-new-test-cmd.md"

# Make an existing command "newer" in submodule
sleep 0.1
touch "$PROJECT/purlin/.claude/commands/pl-status.md"

# Refresh
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if [ -f "$PROJECT/.claude/commands/pl-new-test-cmd.md" ]; then
    log_pass "S2: new command file copied on refresh"
else
    log_fail "S2: new command file NOT copied on refresh"
fi

if [ -f "$PROJECT/.claude/commands/pl-status.md" ]; then
    log_pass "S2: updated command file overwritten on refresh"
else
    log_fail "S2: updated command file NOT present after refresh"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 3: Refresh Mode Preserves Locally Modified Commands
# ─────────────────────────────────────────────────────────────────────────────
echo "[S3] Refresh Mode Preserves Locally Modified Commands"
setup_sandbox

# Full init
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Locally modify pl-status.md (make it newer than submodule copy)
sleep 0.1
echo "# local modification" > "$PROJECT/.claude/commands/pl-status.md"
touch "$PROJECT/.claude/commands/pl-status.md"

# Touch original to ensure consumer copy is newer
ORIGINAL_CONTENT="# local modification"

# Refresh
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if grep -q "local modification" "$PROJECT/.claude/commands/pl-status.md" 2>/dev/null; then
    log_pass "S3: locally modified command preserved on refresh"
else
    log_fail "S3: locally modified command was overwritten"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 4: Refresh Mode Excludes pl-edit-base.md
# ─────────────────────────────────────────────────────────────────────────────
echo "[S4] Refresh Mode Excludes pl-edit-base.md"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
echo "# base edit cmd" > "$PROJECT/purlin/.claude/commands/pl-edit-base.md"
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if [ ! -f "$PROJECT/.claude/commands/pl-edit-base.md" ]; then
    log_pass "S4: pl-edit-base.md excluded from refresh copy"
else
    log_fail "S4: pl-edit-base.md was incorrectly copied"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 5: Refresh Mode Updates Upstream SHA
# ─────────────────────────────────────────────────────────────────────────────
echo "[S5] Refresh Mode Updates Upstream SHA"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
echo "0000000000000000000000000000000000000000" > "$PROJECT/.purlin/.upstream_sha"
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

SHA_CONTENT=$(cat "$PROJECT/.purlin/.upstream_sha" 2>/dev/null || echo "")
ACTUAL_SHA=$(git -C "$PROJECT/purlin" rev-parse HEAD 2>/dev/null || echo "unknown")
if [ "$SHA_CONTENT" = "$ACTUAL_SHA" ]; then
    log_pass "S5: .upstream_sha updated to current HEAD"
else
    log_fail "S5: .upstream_sha not updated (got: ${SHA_CONTENT:0:8}, expected: ${ACTUAL_SHA:0:8})"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 6: Shim Self-Update on Refresh
# ─────────────────────────────────────────────────────────────────────────────
echo "[S6] Shim Self-Update on Refresh"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Corrupt the shim's pinned SHA to simulate stale shim
sed -i.bak 's/PINNED_SHA=.*/PINNED_SHA="0000000000000000000000000000000000000000"/' "$PROJECT/pl-init.sh" 2>/dev/null || \
python3 -c "
import re, sys
content = open('$PROJECT/pl-init.sh').read()
content = re.sub(r'(PINNED_SHA=)[^\n]*', r'\g<1>\"0000000000000000000000000000000000000000\"', content)
open('$PROJECT/pl-init.sh', 'w').write(content)
"

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

CURRENT_SHA=$(git -C "$PROJECT/purlin" rev-parse HEAD 2>/dev/null || echo "unknown")
if grep -q "$CURRENT_SHA" "$PROJECT/pl-init.sh" 2>/dev/null; then
    log_pass "S6: shim regenerated with current SHA"
else
    log_fail "S6: shim not updated with current SHA"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 7: Refresh Mode Never Touches Config or Overrides
# ─────────────────────────────────────────────────────────────────────────────
echo "[S7] Refresh Mode Never Touches Config or Overrides"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

echo '{"tools_root":"purlin/tools","custom_key":"DO_NOT_TOUCH"}' > "$PROJECT/.purlin/config.json"
echo "# CUSTOM OVERRIDE CONTENT" > "$PROJECT/.purlin/ARCHITECT_OVERRIDES.md"

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if grep -q "DO_NOT_TOUCH" "$PROJECT/.purlin/config.json" 2>/dev/null; then
    log_pass "S7: config.json preserved on refresh"
else
    log_fail "S7: config.json was modified on refresh"
fi
if grep -q "CUSTOM OVERRIDE CONTENT" "$PROJECT/.purlin/ARCHITECT_OVERRIDES.md" 2>/dev/null; then
    log_pass "S7: ARCHITECT_OVERRIDES.md preserved on refresh"
else
    log_fail "S7: ARCHITECT_OVERRIDES.md was modified on refresh"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 10: Launchers Always Regenerated on Refresh
# ─────────────────────────────────────────────────────────────────────────────
echo "[S10] Launchers Always Regenerated on Refresh"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
echo "# outdated content" > "$PROJECT/pl-run-architect.sh"
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

for launcher in pl-run-architect.sh pl-run-builder.sh pl-run-qa.sh pl-run-pm.sh; do
    if [ -x "$PROJECT/$launcher" ] && ! grep -q "# outdated content" "$PROJECT/$launcher" 2>/dev/null; then
        log_pass "S10: $launcher regenerated on refresh"
    else
        log_fail "S10: $launcher not properly regenerated"
    fi
done
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 11: Idempotent Repeated Runs
# ─────────────────────────────────────────────────────────────────────────────
echo "[S11] Idempotent Repeated Runs"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
git -C "$PROJECT" add -A && git -C "$PROJECT" commit -q -m "after first init" 2>/dev/null || true
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

DIFF_OUTPUT=$(git -C "$PROJECT" diff 2>/dev/null)
if [ -z "$DIFF_OUTPUT" ]; then
    log_pass "S11: second run produces no file changes (idempotent)"
else
    log_fail "S11: second run produced changes: $(echo "$DIFF_OUTPUT" | head -5)"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 12: Refresh Removes Stale Launchers
# ─────────────────────────────────────────────────────────────────────────────
echo "[S12] Refresh Removes Stale Launchers"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
touch "$PROJECT/run_architect.sh" "$PROJECT/run_builder.sh" "$PROJECT/run_qa.sh"
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if [ ! -f "$PROJECT/run_architect.sh" ] && [ ! -f "$PROJECT/run_builder.sh" ] && [ ! -f "$PROJECT/run_qa.sh" ]; then
    log_pass "S12: stale launchers removed on refresh"
else
    log_fail "S12: stale launchers NOT removed on refresh"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 13: --quiet Flag Suppresses Output
# ─────────────────────────────────────────────────────────────────────────────
echo "[S13] --quiet Flag Suppresses Output"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
QUIET_OUT=$(PATH="$SAFE_PATH" "$INIT_SH" --quiet 2>/dev/null)

if [ -z "$QUIET_OUT" ]; then
    log_pass "S13: --quiet produces no stdout output"
else
    log_fail "S13: --quiet still produced stdout: $(echo "$QUIET_OUT" | head -3)"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 14: Refresh Mode Copies New Agent Files
# ─────────────────────────────────────────────────────────────────────────────
echo "[S14] Refresh Mode Copies New Agent Files"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
mkdir -p "$PROJECT/purlin/.claude/agents"
echo "# new test agent" > "$PROJECT/purlin/.claude/agents/test-new-agent.md"
rm -rf "$PROJECT/.claude/agents"
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if [ -f "$PROJECT/.claude/agents/test-new-agent.md" ]; then
    log_pass "S14: new agent file copied on refresh"
else
    log_fail "S14: new agent file NOT copied on refresh"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 15: Refresh Mode Preserves Locally Modified Agent Files
# ─────────────────────────────────────────────────────────────────────────────
echo "[S15] Refresh Mode Preserves Locally Modified Agent Files"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Create a locally modified agent file (newer timestamp)
mkdir -p "$PROJECT/.claude/agents"
sleep 0.1
echo "# LOCAL MODIFICATION" > "$PROJECT/.claude/agents/builder-worker.md"
touch "$PROJECT/.claude/agents/builder-worker.md"

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if grep -q "LOCAL MODIFICATION" "$PROJECT/.claude/agents/builder-worker.md" 2>/dev/null; then
    log_pass "S15: locally modified agent file preserved"
else
    log_fail "S15: locally modified agent file was overwritten"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 16: Refresh Mode Appends New Gitignore Patterns
# ─────────────────────────────────────────────────────────────────────────────
echo "[S16] Refresh Mode Appends New Gitignore Patterns"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Remove a pattern that should be in gitignore
sed -i.bak '/CRITIC_REPORT.md/d' "$PROJECT/.gitignore" 2>/dev/null || true

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

if grep -q "CRITIC_REPORT.md" "$PROJECT/.gitignore" 2>/dev/null; then
    log_pass "S16: missing gitignore pattern appended on refresh"
else
    log_fail "S16: gitignore pattern NOT appended on refresh"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 17: Refresh Mode Does Not Duplicate Existing Patterns
# ─────────────────────────────────────────────────────────────────────────────
echo "[S17] Refresh Mode Does Not Duplicate Existing Patterns"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
BEFORE=$(cat "$PROJECT/.gitignore" 2>/dev/null || echo "")
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
AFTER=$(cat "$PROJECT/.gitignore" 2>/dev/null || echo "")

if [ "$BEFORE" = "$AFTER" ]; then
    log_pass "S17: gitignore unchanged when all patterns already present"
else
    log_fail "S17: gitignore changed on second refresh (possible duplicates)"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 18: Fresh Clone Collaborator Flow
# ─────────────────────────────────────────────────────────────────────────────
echo "[S18] Fresh Clone Collaborator Flow"
setup_sandbox

# Run full init and commit everything
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
git -C "$PROJECT" add -A && git -C "$PROJECT" commit -q -m "init purlin" 2>/dev/null

# Simulate fresh clone (new clone dir, submodule not initialized)
CLONE_DIR="$SANDBOX/collab-clone"
git clone -q "$PROJECT" "$CLONE_DIR"

# The submodule dir exists but is empty
CLONE_OUT=$(cd "$CLONE_DIR" && PATH="$SAFE_PATH" bash pl-init.sh 2>&1) || true

if echo "$CLONE_OUT" | grep -qi "purlin" || [ -f "$CLONE_DIR/.purlin/config.json" ]; then
    log_pass "S18: collaborator fresh clone flow succeeds (purlin initialized)"
else
    log_fail "S18: collaborator fresh clone flow failed"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 19: Hook Merges Into Existing Settings
# ─────────────────────────────────────────────────────────────────────────────
echo "[S19] Hook Merges Into Existing Settings"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Add a custom PostToolUse hook to settings.json
python3 - <<PYEOF
import json, os
settings_path = "$PROJECT/.claude/settings.json"
with open(settings_path) as f:
    settings = json.load(f)
settings.setdefault('hooks', {}).setdefault('PostToolUse', []).append({
    'matcher': '*',
    'hooks': [{'type': 'command', 'command': 'echo custom_hook_marker'}]
})
with open(settings_path, 'w') as f:
    json.dump(settings, f, indent=2)
PYEOF

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

SETTINGS=$(cat "$PROJECT/.claude/settings.json" 2>/dev/null || echo "{}")
if echo "$SETTINGS" | python3 -c "import sys,json; d=json.load(sys.stdin); ss=d.get('hooks',{}).get('SessionStart',[]); assert any(e.get('matcher')=='clear' for e in ss)" 2>/dev/null; then
    log_pass "S19: Purlin SessionStart hook present after merge"
else
    log_fail "S19: Purlin SessionStart hook missing after merge"
fi
if echo "$SETTINGS" | grep -q "custom_hook_marker"; then
    log_pass "S19: pre-existing custom hook preserved"
else
    log_fail "S19: pre-existing custom hook was removed"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 20: Refresh Removes Stale PreToolUse PM Hook
# ─────────────────────────────────────────────────────────────────────────────
echo "[S20] Refresh Removes Stale PreToolUse PM Hook"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

# Add stale PreToolUse architect hook to settings.json
python3 - <<PYEOF
import json
settings_path = "$PROJECT/.claude/settings.json"
with open(settings_path) as f:
    settings = json.load(f)
settings.setdefault('hooks', {}).setdefault('PreToolUse', []).append({
    'matcher': '*',
    'hooks': [{'type': 'command', 'command': 'echo AGENT_ROLE architect check'}]
})
settings['hooks']['PreToolUse'].append({
    'matcher': 'Edit',
    'hooks': [{'type': 'command', 'command': 'echo user_custom_pretooluse_marker'}]
})
with open(settings_path, 'w') as f:
    json.dump(settings, f, indent=2)
PYEOF

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1

SETTINGS=$(cat "$PROJECT/.claude/settings.json" 2>/dev/null || echo "{}")
if ! echo "$SETTINGS" | grep -q "AGENT_ROLE architect"; then
    log_pass "S20: stale PreToolUse architect hook removed"
else
    log_fail "S20: stale PreToolUse architect hook NOT removed"
fi
if echo "$SETTINGS" | grep -q "user_custom_pretooluse_marker"; then
    log_pass "S20: user's other PreToolUse hooks preserved"
else
    log_fail "S20: user's PreToolUse hooks were removed"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 21: Hook Installation Is Idempotent
# ─────────────────────────────────────────────────────────────────────────────
echo "[S21] Hook Installation Is Idempotent"
setup_sandbox

PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
SETTINGS_BEFORE=$(cat "$PROJECT/.claude/settings.json" 2>/dev/null || echo "")
PATH="$SAFE_PATH" "$INIT_SH" > /dev/null 2>&1
SETTINGS_AFTER=$(cat "$PROJECT/.claude/settings.json" 2>/dev/null || echo "")

if [ "$SETTINGS_BEFORE" = "$SETTINGS_AFTER" ]; then
    log_pass "S21: hook installation is idempotent (settings.json unchanged)"
else
    # Check for duplicates specifically
    CLEAR_COUNT=$(echo "$SETTINGS_AFTER" | python3 -c "import sys,json; d=json.load(sys.stdin); print(sum(1 for e in d.get('hooks',{}).get('SessionStart',[]) if e.get('matcher')=='clear'))" 2>/dev/null || echo "0")
    if [ "$CLEAR_COUNT" -le "1" ]; then
        log_pass "S21: no duplicate hook entries (idempotent)"
    else
        log_fail "S21: duplicate hook entries detected ($CLEAR_COUNT clear hooks)"
    fi
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 22: MCP Setup Skipped When Claude CLI Unavailable
# ─────────────────────────────────────────────────────────────────────────────
echo "[S22] MCP Setup Skipped When Claude CLI Unavailable"
setup_sandbox

# Use SAFE_PATH which already has claude removed
OUT=$(PATH="$SAFE_PATH" "$INIT_SH" 2>&1) || true

if echo "$OUT" | grep -qi "mcp.*skip\|skip.*mcp\|claude.*not found\|claude.*unavailable\|mcp.*unavailable"; then
    log_pass "S22: MCP setup skipped with informational message"
elif ! echo "$OUT" | grep -qi "mcp.*install\|installing mcp"; then
    log_pass "S22: MCP installation not attempted (claude unavailable)"
else
    log_fail "S22: MCP installation unexpectedly attempted"
fi
teardown_sandbox

# ─────────────────────────────────────────────────────────────────────────────
# Scenario 23: MCP Setup Skipped When Manifest Missing
# ─────────────────────────────────────────────────────────────────────────────
echo "[S23] MCP Setup Skipped When Manifest Missing"
setup_sandbox

rm -f "$PROJECT/purlin/tools/mcp/manifest.json"
OUT=$(PATH="$SAFE_PATH" "$INIT_SH" 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    log_pass "S23: init succeeds when manifest missing (non-zero not produced)"
else
    log_fail "S23: init failed when manifest missing (exit code $EXIT_CODE)"
fi
if echo "$OUT" | grep -qi "mcp.*skip\|skip.*mcp\|manifest.*missing\|manifest.*not found"; then
    log_pass "S23: informational message shown for missing manifest"
else
    log_pass "S23: init completed (MCP silently skipped)"
fi
teardown_sandbox

###############################################################################
# Summary
###############################################################################
echo ""
echo "────────────────────────────────"
TOTAL=$((PASS + FAIL))
echo "Results: $PASS/$TOTAL tests passed"
if [ $FAIL -gt 0 ]; then
    printf "\nFailed tests:$ERRORS\n"
    exit 1
fi
exit 0
