#!/bin/bash
# pl-init.sh — Purlin project initialization shim.
# This file is auto-generated by init.sh. Commit it to your repository.
#
# Repo:    git@bitbucket.org:boomerangdev/purlin.git
# SHA:     4432d4b35f2ddeeeb67609372f5efa87632527e8
# Version: RC0.8.4
# Submodule: purlin
#
# Run this script to initialize or refresh the Purlin submodule.
# It works even before the submodule is populated (fresh clone).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INIT_SCRIPT="$SCRIPT_DIR/purlin/tools/init.sh"

if [ ! -f "$INIT_SCRIPT" ]; then
    echo "Initializing submodule purlin..." >&2
    git -C "$SCRIPT_DIR" submodule update --init "purlin"
fi

if [ -f "$INIT_SCRIPT" ]; then
    exec "$INIT_SCRIPT" "$@"
else
    echo "ERROR: Could not find purlin/tools/init.sh after submodule init." >&2
    exit 1
fi
